### PR TITLE
Interface routine for printing convergence history to a file

### PR DESCRIPTION
**Pull request by steffi7574**
Adding an interface routine (C) that can be called after braid_Drive(), in order to print the convergence history (residuals at all iterations) to a file.

### CODE REVIEW

**Comment by jbschroder** [comment]
@steffi7574 @rfalgout 
Is this pull request already covered by braid_SetPrintFile() ?  That is, do we need this code?

**Comment by steffi7574** [comment]
As far as I see it, SetPrintFile() redirects standard braid output into the given file.  But braid_FlushConvHistory() prints the residuals ONLY to a file, in a format that is easier to plot since all the string are removed, i.e. no "Braid:" or "|| r_i || =" strings etc. For me it's very useful for plotting e.g. with gnuplot where I just do a "plot <filename> using 1:2". But not sure if you think it's useful for others.

**Comment by jbschroder** [comment]
@rfalgout 
Thanks Stefanie!  I missed that aspect of this pull request.  This seems like a reasonable feature to have.  What do you think Rob, should we merge?

**Comment by rfalgout** [comment]
I am on the fence about this.  It looks like there is quite a bit of shared functionality here.  I see the point about formatting and making it a bit easier to parse, but maybe that argues for changing the formatting in the current print routine to serve both purposes?  We could just merge it and figure out an alternative solution later.  If so, I would change 'Flush' to something else (Write? Save?).  Also, I would prefer that we use '_braid_' versions of the stdio routines (for the same reasons we do it in hypre) and add '_braid_fprintf'.  This could also be changed later.

So, I'm okay with merging this, but I would like to make a few mods at some future time.

**Comment by jbschroder** [comment]
Hmmm...those are good points.  I think the reason why we prepend "Braid:" for the residual history, is so that if Braid is interfaced with another code, it can be easy to find the "Braid" convergence lines among lots of output.  But since we can already redirect Braid output to a special file, I'm not sure how useful that is.  What do you all think?

Regarding using the braid versions of stdio routines, that makes sense to me.  There is a 
_braid_ParFprintfFlush( )
that is like a braid_fprintf, but for parallel, where only rank 0 prints.

**Comment by jbschroder** [comment]
@steffi7574 @rfalgout 
Ok, I changed the name to braid_WriteConvHistory, and use the _braid_ParFprintFlush() instead of fprintf().  I'd say it's ready to merge at this point, if everyone is supportive.

**Comment by rfalgout** [comment]
Works for me.  Thanks!

**Pull request merged**
